disabled_rules:
  - variable_name
  - function_parameter_count
  - for_where
line_length: 110
type_body_length:
  warning: 300
  error: 400
excluded:
  - Frameworks
  - ReactiveExtensions.playground/
reporter: "xcode"
