# CircleCI version
version: 2.1

jobs:
  build:
    macos:
      xcode: "14.2.0"
    working_directory: ~/ReactiveExtensions
    environment:
      CIRCLE_ARTIFACTS: /tmp

    steps:
      - checkout
      # removed ReactiveSwift submodule and replaced with SPM package.
      # - run: git submodule sync --recursive
      # - run: git submodule update --init --recursive

      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: set -o pipefail &&
          swiftlint lint --strict --reporter json |
          tee $CIRCLE_ARTIFACTS/swiftlint-report.json
      - run:
          name: pre-start simulator iPhone 13 (15.5)
          command: xcrun instruments -w "iPhone 13 (15.5) [" || true
      - run: bin/test iOS 15.5 iPhone 13
      - run:
          name: pre-start simulator iPhone 14 Pro Max (16.2)
          command: xcrun instruments -w "iPhone 14 Pro Max (16.2) [" || true
      - run: bin/test iOS 16.2 iPhone 14 Pro Max

      - store_artifacts:
          path: /tmp/swiftlint-report.json
      - store_artifacts:
          path: /tmp/xcode_raw.log

experimental:
  notify:
    branches:
      only:
        - master
