# CircleCI version
version: 2

jobs:
  build:
    macos:
      xcode: "9.3.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout

      - run: brew install swiftlint
      # - run: set -o pipefail && swiftlint lint --strict --reporter json | tee $CIRCLE_WORKING_DIRECTORY/output/swiftlint-report.json
      - run: bin/test iOS 11.3

# machine:
#   xcode:
#     version: 9.3.0
# dependencies:
#   pre:
#     - brew update || brew update
#     - brew install swiftlint
#     - system_profiler SPSoftwareDataType
#     - security list-keychains
#     - security find-identity -p codesigning
#     - instruments -s devices
#     - xcodebuild -showsdks
#   override:
#     - git submodule sync --recursive
#     - git submodule update --init --recursive
# test:
#   pre:
#     - xcrun instruments -w '547B1B63-3F66-4E5B-8001-F78F2F1CDEA7' || true
#     - sleep 15
#   override:
#     - set -o pipefail &&
#       swiftlint lint --strict --reporter json |
#       tee $CIRCLE_ARTIFACTS/swiftlint-report.json
#     - bin/test iOS 11.2
experimental:
  notify:
    branches:
      only:
        - master
