# CircleCI version
version: 2.1

xcode_version: &xcode_version 14.2.0
iphone_name: &iphone_name iPhone SE (3rd generation)
preload_simulator_iOS_15_5: &preload_simulator_iOS_15_5 xcrun instruments -w "iPhone SE (3rd generation) (15.5) [" || true
preload_simulator_iOS_16_2: &preload_simulator_iOS_16_2 xcrun instruments -w "iPhone SE (3rd generation) (16.2) [" || true

default_environment: &default_environment
  CIRCLE_ARTIFACTS: /tmp
  BUNDLE_PATH: vendor/bundle
  FL_OUTPUT_DIR: output
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  IPHONE_NAME: *iphone_name
  XCODE_VERSION: *xcode_version
  PLATFORM: iOS

jobs:
  build:
    macos:
      xcode: "14.2.0"
    working_directory: ~/ReactiveExtensions
    environment:
      - *default_environment

    steps:
      - checkout
      # removed ReactiveSwift submodule and replaced with SPM package.
      # - run: git submodule sync --recursive
      # - run: git submodule update --init --recursive

      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: set -o pipefail &&
          swiftlint lint --strict --reporter json |
          tee $CIRCLE_ARTIFACTS/swiftlint-report.json
      - run:
          name: Pre-load simulator iOS 15.5
          command: *preload_simulator_iOS_15_5
      - run:
          name: Pre-load simulator iOS 16.2
          command: *preload_simulator_iOS_16_2
      - run: bin/test iOS 15.5
      - run: bin/test iOS 16.2

      - store_artifacts:
          path: /tmp/swiftlint-report.json
      - store_artifacts:
          path: /tmp/xcode_raw.log

experimental:
  notify:
    branches:
      only:
        - master
