# CircleCI version
version: 2

jobs:
  build:
    macos:
      xcode: "11.3.0"
    working_directory: ~/ReactiveExtensions
    environment:
      CIRCLE_ARTIFACTS: /tmp

    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive

      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: set -o pipefail &&
          swiftlint lint --strict --reporter json |
          tee $CIRCLE_ARTIFACTS/swiftlint-report.json
      - run: bin/test iOS 12.4
      - run: bin/test iOS 13.3

      - store_artifacts:
          path: /tmp/swiftlint-report.json
      - store_artifacts:
          path: /tmp/xcode_raw.log

experimental:
  notify:
    branches:
      only:
        - master
