version: 2.1

xcode_version: &xcode_version 14.2.0
iphone_name: &iphone_name iPhone 14 Pro Max
preload_iphone_simulator: &preload_iphone_simulator xcrun instruments -w "iPhone 14 Pro Max (16.2) [" || true
apple_tv_name: &apple_tv_name Apple TV 4K (at 1080p) (2nd generation)
preload_apple_tv_simulator: &preload_apple_tv_simulator xcrun instruments -w "Apple TV 4K (at 1080p) (2nd generation) (16.1) [" || true

# Works around an issue in xcodebuild where it requires GitHub to have been added to the known_hosts in order for it to clone dependencies.
spm_ssh_workaround: &spm_ssh_workaround for ip in $(dig @1.1.1.1 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

# Templates

ios_default_environment: &ios_default_environment
  CIRCLE_ARTIFACTS: /tmp
  BUNDLE_PATH: vendor/bundle
  FL_OUTPUT_DIR: output
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  IPHONE_NAME: *iphone_name
  XCODE_VERSION: *xcode_version
  PLATFORM: iOS

tvos_default_environment: &tvos_default_environment
  CIRCLE_ARTIFACTS: /tmp
  BUNDLE_PATH: vendor/bundle
  FL_OUTPUT_DIR: output
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  IPHONE_NAME: *apple_tv_name
  XCODE_VERSION: *xcode_version
  PLATFORM: tvOS

base_job: &base_job
  macos:
    xcode: *xcode_version
  working_directory: ~/ReactiveExtensions

test_ios_setup_job: &test_ios_setup_job
  steps:
    - checkout
    - run:
        name: SPM SSH Workaround
        command: *spm_ssh_workaround
    - run:
        name: Store Xcode Version
        command: xcodebuild -version > xcode_version.txt
    - restore_cache:
        name: Restore SPM Cache
        keys:
          - spm-cache-v1-{{ checksum "./Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}-{{ checksum "xcode_version.txt" }}
    - run:
        name: Bootstrap SPM
        command: xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath SourcePackages
    - run:
        name: Pre-load iOS simulator
        command: *preload_iphone_simulator
    - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
    - run: set -o pipefail &&
        swiftlint lint --strict --reporter json |
        tee $CIRCLE_ARTIFACTS/swiftlint-report.json
    - run:
        name: Run iOS Tests
        command: xcodebuild test -scheme ReactiveExtensions-iOS -destination platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2
        no_output_timeout: "20m" # 20 minutes
    - store_artifacts:
        path: /tmp/swiftlint-report.json
    - store_artifacts:
        path: /tmp/xcode_raw.log

test_tvos_setup_job: &test_tvos_setup_job
  steps:
    - checkout
    - run:
        name: SPM SSH Workaround
        command: *spm_ssh_workaround
    - run:
        name: Store Xcode Version
        command: xcodebuild -version > xcode_version.txt
    - restore_cache:
        name: Restore SPM Cache
        keys:
          - spm-cache-v1-{{ checksum "./Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}-{{ checksum "xcode_version.txt" }}
    - run:
        name: Bootstrap SPM
        command: xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath SourcePackages
    - run:
        name: Pre-load tvOS simulator
        command: *preload_apple_tv_simulator
    - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
    - run: set -o pipefail &&
        swiftlint lint --strict --reporter json |
        tee $CIRCLE_ARTIFACTS/swiftlint-report.json
    - run:
        name: Run tvOS Tests
        command: xcodebuild test -scheme ReactiveExtensions-tvOS -destination platform=tvOS Simulator,name=Apple TV 4K (at 1080p) (2nd generation),OS=16.1
        no_output_timeout: "20m" # 20 minutes
    - store_artifacts:
        path: /tmp/swiftlint-report.json
    - store_artifacts:
        path: /tmp/xcode_raw.log

# Jobs

jobs:
  # ReactiveExtensions-iOS tests
  reactiveextensions-ios-tests:
    <<: *base_job
    <<: *test_ios_setup_job
    environment:
      - *ios_default_environment
      - SCHEME=ReactiveExtensions-iOS

  # Reactive-Extensions-tvOS tests
  reactiveextensions-tvos-tests:
    <<: *base_job
    <<: *test_tvos_setup_job
    environment:
      - *tvos_default_environment
      - SCHEME=ReactiveExtensions-tvOS

# Workflows
workflows:
  version: 2
  build:
    jobs:
      - reactiveextensions-ios-tests
      - reactiveextensions-tvos-tests

experimental:
  notify:
    branches:
      only:
        - master
